baseURL = "https://sivalabs.in/"
languageCode = "en-us"
title = "SivaLabs"
theme = "wellington"
paginate=10

disqusShortname = "sivalabs"
googleAnalytics = "G-N5019E5MWE"
enableRobotsTXT = true
enableEmoji = true
preserveTaxonomyNames = true
pygmentsCodeFences = true
[taxonomies]
  category = "categories"
  tag = "tags"

[related]
  includeNewer = true
  threshold = 0
  toLower = true

  [[related.indices]]
    name = "categories"
    weight = 100

  [[related.indices]]
    name = "date"
    weight = 10

[params]
  author = "Siva"
  subtitle = "My Experiments with Technology"
  description = "Java, Spring, SpringBoot, SpringCloud, JPA, Hibernate, DevOps, MicroServices, Docker, Kubernetes, AWS tutorials"
  facebook = ""
  twitter = "sivalabs"
  googleplus = ""
  youtube = "sivalabs"
  github = "sivaprasadreddy"
  linkedin = "siva-prasad-reddy-katamreddy"

[social]
  twitter = "sivalabs"
