baseURL = "https://sivalabs.github.io/"
languageCode = "en-us"
title = "SivaLabs"
theme = "wellington"
paginate=10

disqusShortname = "sivalabs"
googleAnalytics = "UA-71296890-1"
enableRobotsTXT = true
preserveTaxonomyNames = true

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  author = "Siva"
  subtitle = "My Experiments with Technology"
  description = "Java, Spring, SpringBoot, SpringCloud, JPA, Hibernate, DevOps, MicroServices, Docker tutorials"
  facebook = ""
  twitter = "sivalabs"
  googleplus = ""
  youtube = "SivaPrasadReddy%20"
  github = "sivaprasadreddy"
  linkedin = "siva-prasad-reddy-k-3a909172"

[social]
  twitter = "sivalabs"
