baseURL = "https://www.sivalabs.in/"
languageCode = "en-us"
title = "SivaLabs"
theme = "wellington"
paginate=10

disqusShortname = "sivalabs"
googleAnalytics = "G-N5019E5MWE"
enableRobotsTXT = true
enableEmoji = true
pygmentsCodeFences = true
[taxonomies]
  category = "categories"
  tag = "tags"

[related]
  includeNewer = true
  threshold = 0
  toLower = true

  [[related.indices]]
    name = "categories"
    weight = 100

  [[related.indices]]
    name = "date"
    weight = 10

[params]
  author = "Siva"
  subtitle = "Java, Kotlin, Spring Boot, SQL, JPA, Architecture, DDD, TDD, REST API, Microservices, DevOps, CI/CD, Docker, Kubernetes Tutorials"
  description = "Java, Kotlin, Go, Spring, Spring Boot, Spring Cloud, SQL, JPA, Hibernate, Kafka, Software Architecture, Domain Driven Design, TDD, REST API, Microservices, DevOps, CI/CD, Docker, Kubernetes, Jenkins, AWS tutorials"
  facebook = ""
  twitter = "sivalabs"
  googleplus = ""
  youtube = "sivalabs"
  github = "sivaprasadreddy"
  linkedin = "siva-prasad-reddy-katamreddy"

[social]
  twitter = "sivalabs"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    #noClasses = false
    noHl = false
    #style = 'onedark'
    tabWidth = 4
