baseURL = "https://www.sivalabs.in/"
title = "SivaLabs"
theme = "sivalabs"

enableRobotsTXT = true
enableEmoji = true
pygmentsCodeFences = true

[menus]
    [[menus.main]]
        name = 'Home'
        pageRef = '/'
        weight = 10

    [[menus.main]]
        name = 'Blog'
        pageRef = '/blog'
        weight = 20

    [[menus.main]]
        name = 'About'
        url = '/about/'
        weight = 70

    [[menus.main]]
        name = 'Conferences'
        url = '/conferences/'
        weight = 40

    [[menus.main]]
        name = 'Books'
        url = '/books/'
        weight = 50

    [[menus.main]]
        name = 'Projects'
        url = '/projects/'
        weight = 60

    [[menus.main]]
        name = 'Courses'
        url = '/courses/'
        weight = 62

    [[menus.main]]
        name = 'Tutorials'
        url = '/tutorials/'
        weight = 65

    [[menus.footer]]
        name = 'About Me'
        url = '/about/'
        weight = 10

[services]
  [services.googleAnalytics]
    id = 'G-N5019E5MWE'
  [services.disqus]
    shortname = 'sivalabs'

[taxonomies]
  category = "categories"
  tag = "tags"

[params.pagination]
  blogPerPage = 12

[related]
  includeNewer = true
  threshold = 0
  toLower = true

  [[related.indices]]
    name = "categories"
    weight = 100

  [[related.indices]]
    name = "date"
    weight = 10

[params]
  subtitle = "Java, Spring Boot, Microservices, Cloud and DevOps Tutorials"
  description = "Java, Spring Boot, JPA, Hibernate, SQL, REST API, Microservices, Architecture, CI/CD, Docker, Kubernetes, Cloud, and DevOps Tutorials"
  publisher = "SivaLabs"
  images = ['/images/Siva.webp']
  [params.author]
  name = 'Siva'
  role = 'Software Developer, Architect, and Developer Advocate'
  image = '/images/Siva.webp'
  bio = 'I am Siva, a passionate software engineer with expertise in building scalable web applications. I enjoy working across the stack and constantly learning new technologies.'
    [[params.author.socials]]
      name = "GitHub"
      url = "https://github.com/sivaprasadreddy"
    [[params.author.socials]]
      name = "LinkedIn"
      url = "https://www.linkedin.com/in/ksivaprasadreddy"
    [[params.author.socials]]
      name = "YouTube"
      url = "https://www.youtube.com/@sivalabs"
    [[params.author.socials]]
      name = "Twitter"
      url = "https://twitter.com/sivalabs"
    [[params.author.socials]]
      name = "Bluesky"
      url = "https://bsky.app/profile/sivalabs.in"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = false
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    #noClasses = false
    noHl = false
    #style = 'onedark'
    tabWidth = 4

[security.http]
mediaTypes = ['^audio/mpeg$']
