baseURL = "https://www.sivalabs.in/"
languageCode = "en-us"
title = "SivaLabs"
theme = "wellington"

enableRobotsTXT = true
enableEmoji = true
pygmentsCodeFences = true

[pagination]
  pagerSize=10

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 2


[services]
  [services.googleAnalytics]
    id = 'G-N5019E5MWE'
  [services.disqus]
    shortname = 'sivalabs'

[taxonomies]
  category = "categories"
  tag = "tags"

[related]
  includeNewer = true
  threshold = 0
  toLower = true

  [[related.indices]]
    name = "categories"
    weight = 100

  [[related.indices]]
    name = "date"
    weight = 10

[params]
  author = "Siva"
  subtitle = "Java, Spring Boot, Microservices, Cloud and DevOps Tutorials"
  description = "Java, Spring Boot, JPA, Hibernate, SQL, REST API, Microservices, Architecture, CI/CD, Docker, Kubernetes, Cloud, and DevOps Tutorials"
  publisher = "SivaLabs"
  images = ['/raw-images/Siva.jpg']
  facebook = ""
  twitter = "sivalabs"
  bluesky = "sivalabs.in"
  youtube = "sivalabs"
  github = "sivaprasadreddy"
  linkedin = "ksivaprasadreddy"
  [params.social]
    twitter = "sivalabs"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = false
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    #noClasses = false
    noHl = false
    #style = 'onedark'
    tabWidth = 4

[security.http]
mediaTypes = ['^audio/mpeg$']