
---
author: Siva
url: jcart-setup-sonarqube-jenkins
title: 'JCart: SetUp SonarQube and Jenkins'
date: 2015-12-13 13:17:45+00:00
Section: post
Description: "In this post we will setup SonarQube and Jenkins to perform code quality check and continuous integration"
categories: ["E-Commerce","Java","JCart","Spring","SpringBoot"]
tags: ["E-Commerce","Java","JCart","Spring","SpringBoot"]
draft: false

---

include::data/ascii-settings.txt[]


In this post we will setup SonarQube and Jenkins to perform code quality check and continuous integration.

== Install and configure SonarQube

There are many code quality checking tools like PMD, Firebug but SonarQube brings them all under one roof 
and gives better view of code quality. 

Let us install and configure SonarQube for our JCart application.

Download SonarQube from http://www.sonarqube.org/downloads/. 
Extract it run *sonarqube-5.2/bin/windows-x86-64/StartSonar.bat*.

By default SonarQube uses in-memory H2 database to store all the metrics.
If we want to use MySQL we can configure MySQL jdbc parameters in *sonarqube-5.2/conf/sonar.properties*

[source, java]
----
sonar.jdbc.url=jdbc:mysql://localhost:3306/sonar
sonar.jdbc.username=root
sonar.jdbc.password=admin
----

=== Configure SonarQube maven Plugin

Let us configure sonarqube maven plugin in jcart/pom.xml

[source, xml]
----
<project xmlns="http://maven.apache.org/POM/4.0.0" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 
	http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.sivalabs</groupId>
	<artifactId>jcart</artifactId>
	<version>1.0</version>
	<packaging>pom</packaging>
	
	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<maven.compiler.source>1.8</maven.compiler.source>
		<maven.compiler.target>1.8</maven.compiler.target>		
		<sonar.jdbc.url>jdbc:mysql://localhost:3306/sonar</sonar.jdbc.url>
      		<sonar.jdbc.username>root</sonar.jdbc.username>
      		<sonar.jdbc.password>admin</sonar.jdbc.password>
	</properties>
	
	...
	...
	
	<build>
		<plugins>
			<plugin>
		       <groupId>org.codehaus.mojo</groupId>
		       <artifactId>sonar-maven-plugin</artifactId>
		       <version>2.7</version>
		     </plugin>
		</plugins>
	</build>
	
</project> 
----

Now you can run maven goal mvn sonar:sonar which performs all the code quality checks and insert metrics into database.
Now go to http://localhost:9000/ and click on jcart project. From there you can explore lot of metrics like coding issues, duplicate code etc.
You can see code quality issue details and fix the problem.

There are lot of things we can configure like tweaking the Quality Profiles to meet our project needs. 
But we are not covering all that in this post now. May be a future post! 

== Install and configure Jenkins

We will be using Jenkins as continuous integration server for JCart.
Download Jenkins war from https://jenkins-ci.org/ and run jenkins as follows:

*java -jar jenkins.war*

Now you can go to http://localhost:8080/ and click on Manage Jenkins to configure JDK, Maven etc.



